### ISSUE TITLE
Admin: Change category name to a more relevant one i.e News category or News.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Sunlite-Australia#39]
![2016-01-05_1746](https://cloud.githubusercontent.com/assets/13309730/12114972/5e2fd564-b3d4-11e5-8aa4-a5e9a43a7085.png)

**Comment by asif-titan** [comment]
As per the knowledge base the default category should be named as Blog Articles with blog-articles as the slug.
![default category](https://cloud.githubusercontent.com/assets/13450796/12179613/da8a5b5a-b59d-11e5-8899-dbd201d7e37d.png)
