### ISSUE TITLE
News-listing page: Incorrect feature image size dimension used.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Sunlite-Australia#54]
Applicable to Projects page also

![untitled-1newsss](https://cloud.githubusercontent.com/assets/13309730/12256917/a2d3c7ae-b927-11e5-8a01-7b6d23ce3cae.png)

**Comment by asif-titan** [comment]
As per Jolene's email on flagging design issues: 
"
I would like you all to flag design or development functionality issues as you are working on a project to your team leader. If the team leader is not sure about the solution then they can raise it with the Perth team (Jo and Ricky) for further assistance. Please keep the following points in mind while working on a project.

1.       Developers to flag designs or functionalities issues earlier

2.       QA team to be in favour of User Experience, meaning if the site functions correctly and the layout looks comparable to the design (does not need to be pixel perfect). If in question please raise with team leader, who can then flag it with the Perth office.

The point of flagging design issues during the build phase is that we can get the designers to amend the design to make the font-end styling easier for the developers as well as informing the design team of design elements which are difficult to develop and not be done in the same way for future layout designs. 
"

This is not a bug.
