### ISSUE TITLE
General Pages - Single View: Inner ordered list is not move to the right a bit so that it will identify clearly that it is a inner list

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Sunlite-Australia#72]
![2016-01-25_1823-projectsingle](https://cloud.githubusercontent.com/assets/13309730/12606127/e1e7d884-c4f0-11e5-8060-d7b22c2f2909.png)

**Comment by asif-titan** [comment]
It is as per the design provided.
