### ISSUE TITLE
Header section: 'Contact Us' Breaks to the next line on IE browser.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Sunlite-Australia#79]
![2016-02-11_1520-ie](https://cloud.githubusercontent.com/assets/13309730/12973657/ec68a420-d0d3-11e5-8780-7e6804138f66.png)

**Comment by asif-titan** [comment]
Please check in IE Edge. It is working fine on my end in IE Edge.

**Comment by mahender-sowedane** [comment]
I'm aware of that, i have tested on IE edge only while testing i found that issue but working fine now.
thanks!
