### ISSUE TITLE
Products-Sub category: Page content in the subcategory page has different styling than the rest of the pages. Bullets marks are not styled.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Sunlite-Australia#87]
![2016-02-19_1420-sub](https://cloud.githubusercontent.com/assets/13309730/13170806/dfe5b656-d714-11e5-886d-69837797ccd9.png)

**Comment by asif-titan** [comment]
Those are not ordered / unordered  lists, that is why the style are not being applied.
![ul-li](https://cloud.githubusercontent.com/assets/13450796/13248560/fb97d054-da44-11e5-8211-036f90beda33.png)

**Comment by mahender-sowedane** [comment]
I think you need to add 'simple-taxonomy-wysiwyg' plugin for this kind of editors.
kindly fix it, thanks!
